# Final Exam - December 6, 2018

# Set 1

## A. Dictionaries

#### 1. Create two dictionaries: PersonalInfo with 7 key-value pairs & WorkInfo with 4 key-value pairs
Ex: First name - John, Last name - Doe, Age - 25, Address - 111 North Street, Phone - (312) 235-5584, etc... and 

Work address - 123 South street, Phone - (630) 787-4453, etc...

In [102]:
PersonalInfo = {"First Name" : 'Jad',
                "Last Name" : 'Elgaali',
                "Phone #" : '(773) 123-4567',
                "email" : 'jelgaali@gmail.com',
                "address" : '100 E 32nd Street',
                "Apt #" : '2201',
                "Marital Status" : 'Single'}

WorkInfo = {"Employer" : 'University of Chicago',
            "Address" : '450 Cityfront Plaza Dr',
            "Work email" : 'jelgaali@uchicago.edu',
            "Department" : 'Biomedical informatics'}

#### 2. Add a new pair key-value to the dictionary PersonalInfo and remove a key-value pair from WorkInfo. Print results after the 2 operations

In [107]:
PersonalInfo = {"First Name" : 'Jad',
                "Last Name" : 'Elgaali',
                "Phone #" : '(773) 123-4567',
                "email" : 'jelgaali@gmail.com',
                "address" : '100 E 32nd Street',
                "Apt #" : '2201',
                "Marital Status" : 'Single'}

WorkInfo = {"Employer" : 'University of Chicago',
            "Address" : '450 Cityfront Plaza Dr',
            "Work email" : 'jelgaali@uchicago.edu',
            "Department" : 'Biomedical informatics'}



PersonalInfo.update({"Age":'23',"Employment":'Student'})

del WorkInfo["Employer"]

WorkInfo.update({"Work Status" : 'Part Time'})

print("The personal info update:", PersonalInfo)
print("The work info updated:",WorkInfo)

The personal info update: {'First Name': 'Jad', 'Last Name': 'Elgaali', 'Phone #': '(773) 123-4567', 'email': 'jelgaali@gmail.com', 'address': '100 E 32nd Street', 'Apt #': '2201', 'Marital Status': 'Single', 'Age': '23', 'Employment': 'Student'}
The work info updated: {'Address': '450 Cityfront Plaza Dr', 'Work email': 'jelgaali@uchicago.edu', 'Department': 'Biomedical informatics', 'Work Status': 'Part Time'}


#### 3. Concatenate the 2 dictionaries and print all 3 dictionaries. Iterate through the compound dictionary by printing every key-value pair, each on one line

In [108]:
CombinedInfo = {}

for dic in (PersonalInfo, WorkInfo):
    CombinedInfo.update(dic)

print("The new combined info dictionary is:\n",CombinedInfo)

The new combined info dictionary is:
 {'First Name': 'Jad', 'Last Name': 'Elgaali', 'Phone #': '(773) 123-4567', 'email': 'jelgaali@gmail.com', 'address': '100 E 32nd Street', 'Apt #': '2201', 'Marital Status': 'Single', 'Age': '23', 'Employment': 'Student', 'Address': '450 Cityfront Plaza Dr', 'Work email': 'jelgaali@uchicago.edu', 'Department': 'Biomedical informatics', 'Work Status': 'Part Time'}


#### 4. Sort the compound dictionary by keys in descending order and print on record per line

In [109]:
CombinedInfo
newList = print(sorted(CombinedInfo)[::-1])

['email', 'address', 'Work email', 'Work Status', 'Phone #', 'Marital Status', 'Last Name', 'First Name', 'Employment', 'Department', 'Apt #', 'Age', 'Address']


## B. numpy

#### 5. Create and print a numpy 1-d array containing 25 decimal numbers that starts at 1 and end at 7. Calculate and print the min, max and avarage value of this 1-d array

In [88]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,1.1,1.2,1.3,2.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,1.1,], dtype = float)
a
  

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 1.1, 1.2, 1.3, 2.1, 1.1, 1.1,
       1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1])

In [85]:
a.min()

1.0

In [86]:
a.max()

7.0

In [87]:
a.mean()

1.964

#### 6. Create and print a 2 dimensional array A that has 16 rows and 4 columns composed of consecutive integers. Change the shape of the array A to a new array B that has 8 rows and 8 columns and print it out

In [23]:
from numpy  import *
a = np.arange(64).reshape(16, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63]])

In [24]:
#part 6b

b = arange(64).reshape(8,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

#### 7. Add "elementwise" the numpy array obtained above (B) with the appropriate size identity array. Print the results

In [32]:
c = np.eye(8,8, dtype=int)
d = b+c
print(d)

[[ 1  1  2  3  4  5  6  7]
 [ 8 10 10 11 12 13 14 15]
 [16 17 19 19 20 21 22 23]
 [24 25 26 28 28 29 30 31]
 [32 33 34 35 37 37 38 39]
 [40 41 42 43 44 46 46 47]
 [48 49 50 51 52 53 55 55]
 [56 57 58 59 60 61 62 64]]


#### 8. Multiply "dot-style" the numpy array obtained from summation with the array B and print the results

In [35]:
dot(b,d)

array([[ 1120,  1149,  1178,  1207,  1236,  1265,  1294,  1323],
       [ 2920,  3013,  3106,  3199,  3292,  3385,  3478,  3571],
       [ 4720,  4877,  5034,  5191,  5348,  5505,  5662,  5819],
       [ 6520,  6741,  6962,  7183,  7404,  7625,  7846,  8067],
       [ 8320,  8605,  8890,  9175,  9460,  9745, 10030, 10315],
       [10120, 10469, 10818, 11167, 11516, 11865, 12214, 12563],
       [11920, 12333, 12746, 13159, 13572, 13985, 14398, 14811],
       [13720, 14197, 14674, 15151, 15628, 16105, 16582, 17059]])

## C. pandas

#### 9. Load data from the File-input.csv file into a pandas dataframe and print it to the Jupyter console

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
import operator 
dataFrame = pd.read_csv("File-input.csv")
print(dataFrame)

   First name Last name  Age           Phone   Temp Height  Weight  \
0       David      Kain   78  (312) 524-6685   99.9  5'11"     178   
1       Kevin    O'Hara   56  (312) 897-3358  102.5   6'2"     185   
2        Kara     Smith   37  (312) 895-2258   97.2   6'3"     215   
3       Blair     Steel   67  (202) 323-5687   98.9  5'11'     168   
4       Marie   Collins   54  (312) 564-2552  101.0   6'0"     158   
5     Michael    Jordan   55  (312) 532-9985   99.9   6'5"     192   
6       Peter    Arnold   23  (773) 528-8854   97.2   5'8"     165   
7        John  McKenzie   43  (312) 326-5541   98.2   6'2"     195   
8      Joanna     Jones   25  (773) 954-8854  101.2   5'9"     145   
9     MaryLou   Andrews   34  (312) 253-2672   98.0   5'6"     154   
10        Jon   Clinton   85  (312) 321-9922  102.2   5'5"     178   
11       Andy      Bush   44   (773)777-8833   98.5   5'8"     165   

             City  
0         Chicago  
1        Winnetka  
2        Oakbrook  
3        

#### 10. Convert the dataframe into a list of Dictionaries using the .to_dict method and then save all the records from the pandas dataframe as different dictionaries. Orient them as 'records' and print them on different lines

In [38]:
result = dataFrame.to_dict(orient='records')

for row in result:
    dict = row.copy()
    print(dict)

{'First name': 'David', 'Last name': 'Kain', 'Age': 78, 'Phone': '(312) 524-6685', 'Temp': 99.9, 'Height': '5\'11"', 'Weight': 178, 'City': 'Chicago'}
{'First name': 'Kevin', 'Last name': "O'Hara", 'Age': 56, 'Phone': '(312) 897-3358', 'Temp': 102.5, 'Height': '6\'2"', 'Weight': 185, 'City': 'Winnetka'}
{'First name': 'Kara', 'Last name': 'Smith', 'Age': 37, 'Phone': '(312) 895-2258', 'Temp': 97.2, 'Height': '6\'3"', 'Weight': 215, 'City': 'Oakbrook'}
{'First name': 'Blair', 'Last name': 'Steel', 'Age': 67, 'Phone': '(202) 323-5687', 'Temp': 98.9, 'Height': "5'11'", 'Weight': 168, 'City': 'DC'}
{'First name': 'Marie', 'Last name': 'Collins', 'Age': 54, 'Phone': '(312) 564-2552', 'Temp': 101.0, 'Height': '6\'0"', 'Weight': 158, 'City': 'Chicago'}
{'First name': 'Michael', 'Last name': 'Jordan', 'Age': 55, 'Phone': '(312) 532-9985', 'Temp': 99.9, 'Height': '6\'5"', 'Weight': 192, 'City': 'Chicago'}
{'First name': 'Peter', 'Last name': 'Arnold', 'Age': 23, 'Phone': '(773) 528-8854', 'Temp

#### 11. Access and print the 2nd dictionary as 2nd record of the pandas dataframe

In [39]:
n = 1 # This is the fourth index, or the third element
print(result[n])

{'First name': 'Kevin', 'Last name': "O'Hara", 'Age': 56, 'Phone': '(312) 897-3358', 'Temp': 102.5, 'Height': '6\'2"', 'Weight': 185, 'City': 'Winnetka'}


#### 12. List all the keys of this dictionary, one per line, and then create a list with the them called “headers”

In [40]:
dict = result[n]

for key in dict.keys():
   print(key)
print()

headers = list(dict.keys())
print(headers)

First name
Last name
Age
Phone
Temp
Height
Weight
City

['First name', 'Last name', 'Age', 'Phone', 'Temp', 'Height', 'Weight', 'City']


#### 13. Select and print the 4th element in the list

In [41]:
headers[3]

'Phone'

#### 14. Modify the values for "Temp" and "Weight" keys for this specific record

In [43]:
dict["Temp"] = 99
dict["Weight"] = 173
print(list(dict.values()))

['Kevin', "O'Hara", 56, '(312) 897-3358', 99, '6\'2"', 173, 'Winnetka']


#### 15. Find the "First name" that has the Min value of "Weight" from the dataframe

In [59]:
# Reduce size of dataframe to just 2 columns of interest
df = dataFrame[['First name','Weight']] # index names are case sensitive 
result = df.to_dict(orient='records')

# Find the minvalue and create a Tuple
min = 1000000
solution = ((),)
for row in result:
    weight = row['Weight']
    firstname = row['First name']
    if weight < min:
        min = weight
        solution = firstname, weight
print(solution)

('Joanna', 145)
