In [5]:
import numpy as np

In [16]:
# 1 Create a numpy array from 3 nested Py lists

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# 1 then print its shape

shape = a.shape

print("The shape of the array is:",shape)

The shape of the array is: (3, 3)


In [94]:
# 1 and access the 3 diagonal elements

diag = a.diagonal()

print("The diagonal elements are:", diag)

The diagonal elements are: [1 5 9]


In [18]:
# 2 Create a numpy array with 3 rows and 5 columns filled with zeros

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# 3 Create a numpy array with 8 columns and 5 rows filled with ones

np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
# 4 Create a 7x7 identity matrix

np.eye(7,7, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [108]:
# 5 Create a constant array of size (3 x 7) filled with floats

ca = np.full((3,7), 2.9, dtype=float)
ca

array([[2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9]])

In [36]:
# 6 Create an array of size (8 x 3) filled with random values

np.random.rand(8,3)

array([[0.10245098, 0.99441511, 0.92912122],
       [0.93192204, 0.25496534, 0.44024087],
       [0.88928896, 0.68522975, 0.61670198],
       [0.81765855, 0.02299416, 0.96328577],
       [0.79652573, 0.77808105, 0.38160693],
       [0.01659936, 0.59918226, 0.97603575],
       [0.33230566, 0.04220391, 0.79584499],
       [0.76796011, 0.47667155, 0.85590121]])

In [45]:
# 7 Create an array of rank 2 with shape (7, 4)

from numpy import *

y = arange(28).reshape(7,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [89]:
# 8 Create 2 numpy arrays and do arithmetic operations on them

A = array( [[1,1],
             [3,1]] )
B = array( [[2,1],
             [7,3]] )

print(A+B) #sum

print(A-B) #difference

print(A*B) #multiplication

print(A/B) #division

[[ 3  2]
 [10  4]]
[[-1  0]
 [-4 -2]]
[[ 2  1]
 [21  3]]
[[0.5        1.        ]
 [0.42857143 0.33333333]]


In [90]:
# 9 Create 2 numpy arrays and do "dot" multiplication of them

p = array([[1,7],[2,5]])
q = array([[2,9],[7,1]])
dot(p,q)

array([[51, 16],
       [39, 23]])

In [116]:
# 10 Show a Broadcasting example: add the vector v to each row of the matrix x, then store the result in the matrix y

v = np.array([0, 1, 2])
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.empty_like(x)

y=x+v

print("The vector v is:\n",v)
print("\nThe matrix x is:\n",x)
print("\nThe resultant matrix y is:\n",y)

The vector v is:
 [0 1 2]

The matrix x is:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

The resultant matrix y is:
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
